### ISSUE TITLE
consider switch to sparkleUpdateProcessor for Things 

### ISSUE THREAD

**Issue by arubdesu** [autopkg/valdore86-recipes#1]
Hey there, I believe there was some reluctance to use macupdate as a source to poll, especially when there is a SUFeedURL value in the Things app bundle, and curl'ing it returns info and a valid CDN download:

```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle" version="2.0">
<channel>
<title>Things Updates</title>
<link>http://culturedcode.cachefly.net/things/leopard/sparkle/sparkle_1.4.8_en.xml</link>
<description>Release Versions</description>
<language>en</language>
<item>
<title>Version 1.4.8</title>
<description></description>
<sparkle:releaseNotesLink>http://culturedcode.cachefly.net/things/leopard/sparkle/notes_1.4.8_en.html</sparkle:releaseNotesLink>
<pubDate>Wed, 20 July 2011 18:27:05 +0200</pubDate>
<enclosure sparkle:shortVersionString="1.4.8" sparkle:version="1480" url="http://culturedcode.cachefly.net/things/Things_1.4.8a.zip" length="8977920" type="application/octet-stream" sparkle:dsaSignature="MCwCFCLnU5a/SoTgpZQiFZpJWzxhwwV8AhRKkh+rNFVKXNZHKoh9pCOyp0Carw==" />
</item>
</channel>
</rss>
```

Please pardon the request/recommendation this recipe gets migrated to using that instead. Thanks!

**Comment by fonteijnf** [comment]
Hi there, 

you are totally right about it being better to use sparkle, but in this case I'd have to say I saw no other way. The sparkle link still refers back to Things 1.4.8 when 2.5.4 is already out! Darn Cultured Code. And they only seem to offer it through AppStore. 

I do like this work by nmcspadden https://github.com/autopkg/nmcspadden-recipes/tree/master/AppStoreApp, but this recipe is quicker. I do very much consider moving to sparkleupdate if Cultured Code ever updates the sparkle.

**Comment by arubdesu** [comment]
Huh. Guess you need the useragent
![screen shot 2015-07-04 at 10 43 48 am](https://cloud.githubusercontent.com/assets/388808/8508327/e22aaab0-2239-11e5-8d68-8923249aaeb3.png)

**Comment by fonteijnf** [comment]
I've been trying to get the result you are showing, but I can't get it right. Ah well... the sparkle however is perfect! Thank you very much! I've put it in the recipe right away.

**Comment by arubdesu** [comment]
Yeah, Charles takes a little getting used to. When a vendor uses https for their feed URL you need to add it in SSL Proxy Settings from the Proxy menu
![screen shot 2015-07-06 at 1 34 50 pm](https://cloud.githubusercontent.com/assets/388808/8528836/dcf2c798-23e3-11e5-9256-528c5c81b149.png)
