### ISSUE TITLE
Visual Studio Code Helper

### ISSUE THREAD

**Issue by BaddMann** [autopkg/valdore86-recipes#11]
I've built a recipe for VS code as well. (Mostly a Robot Recipe, with a few small tweaks).
What I've not created or you by the looks of your recipe code is a way to install VScode's helper object that keeps bugging my users.

Any advice or experience on installing the vscode helper via a munki recipe?

**Comment by BaddMann** [comment]
Let me Correct my previous post by saying this appears to be caused by extensions and Admin access.
![screen shot 2016-10-19 at 9 37 03 am](https://cloud.githubusercontent.com/assets/211092/19528175/d6491996-95df-11e6-8f82-4358d1232d94.png)

**Comment by fonteijnf** [comment]
We are also running our Macs with an admin account and user account, but I've only ever seen this appear whenever Code felt like there was an update and the update hadn't come in via Munki yet. 'Ever' used to be a lot before my recipe got fixed (someone helped me), but now when all AutoPkg recipes are run in the morning I never see this pop-up for helper tool anymore.

... having said that. Wouldn't it be nice if Code could update itself as well? I'm going to take a look at it.

**Comment by fonteijnf** [comment]
I totally forgot about this, but haven't had any issues with this myself at all since this.
