### ISSUE TITLE
Things.download.recipe SPARKLE_FEED_URL

### ISSUE THREAD

**Issue by blackthroat** [autopkg/valdore86-recipes#15]
`SPARKLE_FEED_URL` downloads version `2.8.12` while the newest version (`3.2`) can be downloaded from `https://culturedcode.com/things/download/`

**Comment by fonteijnf** [comment]
Hi blackthroat.

Sadly I can not update the recipes beyond 2.8.
Cultured code only offers a trial version from that link that can not be updated to a full licensed version unless you are willing to play around with copying the MAS receipt from a purchased version (from Mac App Store).

I'm going to remove the Things.recipes

If you want to keep using Autopkg for Things3 I suggest looking at https://github.com/autopkg/nmcspadden-recipes/tree/master/AppStoreApp
If it's for personal use it's totally fine.

If you are planning on using it for a company you'll need to look into Apple VPP
