### ISSUE TITLE
Please update Azure Data Studio for version 1.8.0

### ISSUE THREAD

**Issue by hugo4711** [autopkg/valdore86-recipes#19]
1.8.0 has been released:
https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017

It seems that the recipe is not getting the current version. I am stuck on 1.5.2

**Comment by fonteijnf** [comment]
HI Hugo,

the developers had changed the download-ID I had been using. I fixed it in the recipe and just tested it and I got the new version. Please let me know if you notice something like this again.
Thank you for notifying me about the issue!

https://github.com/autopkg/valdore86-recipes/commit/0d72841808f0939245d890d37e968e99c5a60cdf
