### ISSUE TITLE
hardcoded MySQLWorkbench version

### ISSUE THREAD

**Issue by arubdesu** [autopkg/valdore86-recipes#2]
@cgerke has this product in his repo, and he seems to be hitting [a page](https://github.com/autopkg/cgerke-recipes/blob/master/Applications/MySQLWorkBench.download.recipe#L26) with the most recently available GA version. If I'm missing something and this is more optimal in some way, folks usually put a note explaining such in their readme as a courtesy. 
You could also consider renaming it as folks may be confused which version of the recipe they're running if they don't understand autopkg's search order. Pardon me again for being nosy.

**Comment by fonteijnf** [comment]
Removed it for now. Will add some more valuable things...
