### ISSUE TITLE
Code signature verification failed

### ISSUE THREAD

**Issue by arekdist** [autopkg/valdore86-recipes#21]
The following recipes failed:
    CommanderOne.munki
        Error in local.munki.CommanderOne: Processor: CodeSignatureVerifier: Error: Code signature verification failed. Note that all verifications can be disabled by setting the variable DISABLE_CODE_SIGNATURE_VERIFICATION to a non-empty value.

**Comment by fonteijnf** [comment]
This is a weird issue dear arekdist. Usually people leave a problem and don't just simply copy paste a whole error. Last part obviously states how to locally and temporarily solve your issue, but I am guessing you would have liked to ask me to fix the recipe ;-)

I will soon!

**Comment by arekdist** [comment]
Thanks for fixing recipe! It works now.
