### ISSUE TITLE
Changed link for download in CommanderOne recipe

### ISSUE THREAD

**Issue by arekdist** [autopkg/valdore86-recipes#22]
They changed link for CommanderOne download:

https://cdn.electronic.us/products/commander/mac/download/commander.dmg

Please update.

**Comment by fonteijnf** [comment]
Thank you for noticing! I thought the original linked worked just fine, but apparently it was still pulling version 2.3.1. Checked out the new link via their RSS and seems all fine so replaced the download link with the one you suggested.
