### ISSUE TITLE
Harvest has moved to a App Store only model

### ISSUE THREAD

**Issue by Daz-wallace** [autopkg/valdore86-recipes#28]
When launching the current version of the App, after a login, the user is told they need to remove this version and install direct from the Mac App Store.

Checking their website, the download page redirects to this page https://www.getharvest.com/apps/mac with only the App store link.

It looks like it might be worth decommissioning the recipes but I'll leave that choice to you 😊

**Comment by fonteijnf** [comment]
Hi Daz-wallace.
I have stopped using this app actively for quite a while, so I thank you for bringing this to my attention.
I will decommission these recipes.

**Comment by fonteijnf** [comment]
Thanks again Daz-wallace!
I've just added a deprecation warning and will be removing them shortly.
https://github.com/autopkg/valdore86-recipes/commit/0ba4a828c8b1baf19863f713320a537a02b6259a
