### ISSUE TITLE
Robo 3T is now Studio 3T

### ISSUE THREAD

**Issue by paul-cossey** [autopkg/valdore86-recipes#33]
Hi, @valdore86 

Robo 3T has been discontinued and replaced with a new Application called Studio 3T

Further info is available here: https://robomongo.org and https://blog.robomongo.org/studio3t-free/

**Comment by fonteijnf** [comment]
Hi Paul,

I've done a bit of renaming and a bit of simplifying the recipe so it can still be used to get Legacy Robo3T. I've also added a deprecation warning. Ater doing that I've added Studio 3T recipes with support for Intel and Apple Silicon.
https://github.com/autopkg/valdore86-recipes/tree/master/Studio%203T

I hope that addresses your issue 😊 

kind regards,
Frank
