### ISSUE TITLE
Microsoft Remote Desktop Munki recipe problem

### ISSUE THREAD

**Issue by opus-nbonenberger** [autopkg/valdore86-recipes#38]
@valdore86 Your munki recpie for Microsoft Remote Desktop needs an installs array for the app to compare the CFBundleShortVersionString. Without it, Managed Software Center downloads the App on every run. Can you adjust this? Thanks!

**Comment by fonteijnf** [comment]
MunkiImporter Processor automatically creates the installs array when importing to Munki.
