### ISSUE TITLE
VisualStudioCode recipe giving error 403 (includes suggested fix)

### ISSUE THREAD

**Issue by jelockwood** [autopkg/valdore86-recipes#40]
@valdore86 
As of last night your VisualStudioCode download recipe is giving the following error.

`curl: (56) The requested URL returned error: 403`

I made a copy of your download recipe and did a test of what I suspected was the cause and have confirmed it. Microsoft are now checking the user-agent of the downloading app and looking for it to be a Mac web-browser. You therefore need to change your recipe to the following.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Description</key>
	<string>Downloads the current release version of Visual Studio Code.</string>
	<key>Identifier</key>
	<string>com.github.valdore86.download.visualstudiocode</string>
	<key>Input</key>
	<dict>
		<key>NAME</key>
		<string>Visual Studio Code</string>
		<key>USER_AGENT</key>
		<string>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/536.28.10 (KHTML, like Gecko) Version/6.0.3 Safari/536.28.10</string>
	</dict>
	<key>MinimumVersion</key>
	<string>1.0.4</string>
	<key>Process</key>
	<array>
		<dict>
			<key>Arguments</key>
			<dict>
				<key>filename</key>
				<string>vscode.zip</string>
				<key>url</key>
				<string>https://code.visualstudio.com/sha/download?build=stable&amp;os=darwin-universal</string>
				<key>request_headers</key>
				<dict>
					<key>user-agent</key>
					<string>%USER_AGENT%</string>
				</dict>
			</dict>
			<key>Processor</key>
			<string>URLDownloader</string>
		</dict>
		<dict>
			<key>Processor</key>
			<string>EndOfCheckPhase</string>
		</dict>
		<dict>
			<key>Arguments</key>
			<dict>
				<key>archive_path</key>
				<string>%pathname%</string>
				<key>destination_path</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%</string>
				<key>purge_destination</key>
				<true/>
			</dict>
			<key>Processor</key>
			<string>Unarchiver</string>
		</dict>
		<dict>
			<key>Arguments</key>
			<dict>
				<key>input_path</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%/Visual Studio Code.app</string>
				<key>requirement</key>
				<string>identifier "com.microsoft.VSCode" and anchor apple generic and certificate 1[field.1.2.840.113635.100.6.2.6] /* exists */ and certificate leaf[field.1.2.840.113635.100.6.1.13] /* exists */ and certificate leaf[subject.OU] = UBF8T346G9</string>
			</dict>
			<key>Processor</key>
			<string>CodeSignatureVerifier</string>
		</dict>
		<dict>
			<key>Arguments</key>
			<dict>
				<key>input_plist_path</key>
				<string>%RECIPE_CACHE_DIR%/%NAME%/Visual Studio Code.app/Contents/Info.plist</string>
				<key>plist_version_key</key>
				<string>CFBundleShortVersionString</string>
			</dict>
			<key>Processor</key>
			<string>Versioner</string>
		</dict>
	</array>
</dict>
</plist>
```

**Comment by fonteijnf** [comment]
@jelockwood are you still having this issue? I imported a new Visual Studio Code on the 16th of October without making changes to the recipe.

**Comment by jelockwood** [comment]
@valdore86 
I have been running my copy with my 'fix' whilst awaiting your response and my copy still works fine. I have just re-tested your copy which - yes I can see is still unchanged. I can confirm for me your copy is still broken.

See this screen capture. It is from AutoPkgr but that is merely a GUI front-end to the standard AutoPkg.

![Screenshot 2024-10-17 at 11 49 54](https://github.com/user-attachments/assets/cc856e2b-72f3-4e56-b144-6999c1fb484d)

My copy with my fix can be viewed and tried at the following link

https://github.com/jelockwood/recipes/tree/master/Visual%20Studio%20Code

**Comment by fonteijnf** [comment]
@jelockwood Should be resolved now.
I have never structurally used AutoPkgr, so I wonder why AutoPkgr doesn't want to run this without `USER AGENT`.
My launch daemon triggered autopkg script had no issues 😊

**Comment by jelockwood** [comment]
@valdore86 
I can confirm your download recipe now works in AutoPkgr. Many thanks, I will delete my copy.

Note: Your recipe was in the past working in AutoPkgr so it was not merely an incompatibility with AutoPkgr but also a Microsoft change. I would presume that AutoPkg defaults to sending a user-agent value and AutoPkgr defaults to not sending a user-agent value but that is just a guess.
