### ISSUE TITLE
Visual Studio Code recipe won't download anything newer than 1.5.2

### ISSUE THREAD

**Issue by chelming** [autopkg/valdore86-recipes#9]
The link used for Visual Studio Code has the hash of the 1.5.2 commit in it, so it won't download any newer releases.

The AutoPkg github processor can't be used because even though Microsoft has tags for versions, none of them are actually marked as releases and won't work until https://github.com/Microsoft/vscode/issues/1230 is closed.

https://go.microsoft.com/fwlink/?LinkID=620882 _should_ dynamically download the latest version (similar to the links on http://macadmins.software/)

**Comment by fonteijnf** [comment]
I humbly accept your contribution. Thank you very much Chris!

I had been looking for a link to make it work regardless of version number or hash, but I hadn't put much effort in it. Thank you for doing so. Also thanks for adding CodeSignatureVerifier support.
